"""forgot_password_token

Revision ID: 189f7fe29b88
Revises: f60b00e1b376
Create Date: 2025-03-11 04:09:29.510033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189f7fe29b88'
down_revision = 'f60b00e1b376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forgot_password_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('forgot_password_token')

    # ### end Alembic commands ###
